# Generated by Django 3.2.9 on 2021-11-14 10:36

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter 10 digits phone number', max_length=128, region=None, unique=True, validators=[django.core.validators.RegexValidator('^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$')], verbose_name='Phone Number'),
        ),
    ]
