# Generated by Django 3.2.9 on 2021-11-14 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Enter 10 digits phone number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^(03|05|07|08|09|01[2|6|8|9])+([0-9]{8})$')], verbose_name='Phone Number'),
        ),
    ]
